### ISSUE TITLE
Ambiguos redirection on nutanix-guest-tools-reporting-v_1.0.sh

### ISSUE THREAD

**Issue by PeterGarlic** [magander3/reporting#2]
on bash (GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu) the redirection of output to $file return the error "$file: ambiguous redirect" and doesn't write to file
use double quota  "$file" to fix

**Comment by magander3** [comment]
Ok, thanks for letting me know. "" works on MacBook as well, where I tested without the "" so I'll change and upload a new version.

**Comment by PeterGarlic** [comment]
Great job! i continue the testing.... ;D
