### ISSUE TITLE
ahv-vm-reporting-v_2.2.sh - error with comma in description field

### ISSUE THREAD

**Issue by PeterGarlic** [magander3/reporting#3]
if the VM desciption contain a comma (,) the output csv format line is disaligned

**Comment by magander3** [comment]
good point, never tested. Need to figure that out, easiest would be to let the script either remove the comma or change it to e.g. dot (.) but that is kind a ugly..

**Comment by magander3** [comment]
solved now. wrapping in the description filed in double quotes which means it will be aligned when doing e.g. text-to-columns based on common in Excel.
