### ISSUE TITLE
newline on output filename on nutanix-guest-tools-reporting-v_1.0.sh

### ISSUE THREAD

**Issue by PeterGarlic** [magander3/reporting#4]
on our environment (AOS 5.6.2)  the rest api call:
getcluster=`curl -k -u $user:$passwd -X GET --header 'Accept: application/json' $urlgetcluster`
return 2 times the value "name": 1 for the calling host, one for the cluster name.
This split the filename in two parts and generate one incorrect filename.

to solve th issue I added:  | tail -1 
to the the following code line:

`# Find cluster name`
`clustername=`echo $getcluster | python -m json.tool | grep -w name | awk -F "\"" '{print $4}' | awk -F " " '{print $1}'`

**Comment by magander3** [comment]
what names did you get from the output (cluster and model) ?

**Comment by magander3** [comment]
what if you use
$clustername=`echo $getcluster | python -m json.tool | grep -A 1 multicluster | grep -w name | awk -F "\"" '{print $4}' | awk -F " " '{print $1}'`

?

**Comment by magander3** [comment]
ok, that's strange. can you echo the $getcluster to a file and send it to me pmandersson1978@gmail.com ?

**Comment by magander3** [comment]
Uploaded ver 1.1 with the correct cluster name command
